version: '3.3'

services:
  php:
    build: .
    restart: always
    ports:
      - 8080:80
    working_dir: /var/www/html/OfferConfigurator
    volumes:
      - .:/var/www/html/OfferConfigurator
    networks:
      - dev

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 8088:80
    environment:
      PMA_HOST: mysql
    networks:
      - dev

networks:
  dev:
